# Generated by Django 4.2.7 on 2023-12-26 03:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('saving_throw', models.CharField(max_length=2000, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('range', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpellListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('character_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_class_spell_list_item', to='hyperborea.characterclass')),
                ('spell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell_spell_list_item', to='hyperborea.spell')),
            ],
        ),
    ]
