# Generated by Django 4.2.7 on 2023-12-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperborea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
