# Generated by Django 4.2.7 on 2023-12-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperborea', '0002_alter_characterclass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='saving_throw',
            field=models.CharField(default='None', max_length=2000, null=True),
        ),
    ]
