# Generated by Django 4.2.7 on 2023-12-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperborea', '0003_alter_spell_saving_throw'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='reversible',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
