# Generated by Django 4.2.7 on 2023-12-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperborea', '0005_spell_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
