# Generated by Django 4.2.7 on 2023-12-27 20:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyperborea', '0007_remove_spell_reversible'),
    ]

    operations = []
