# Generated by Django 4.2.7 on 2023-12-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyperborea', '0008_characterclass_spelllistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spelllistitem',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='spelllistitem',
            name='spell',
        ),
        migrations.DeleteModel(
            name='CharacterClass',
        ),
        migrations.DeleteModel(
            name='SpellListItem',
        ),
    ]
