# Generated by Django 4.2.7 on 2023-12-28 22:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyperborea', '0010_spell_cleric_level_spell_cryomancer_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spell',
            name='cleric_level',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='cryomancer_level',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='druid_level',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='illusionist_level',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='magician_level',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='necromancer_level',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='pyromancer_level',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='witch_level',
        ),
        migrations.CreateModel(
            name='SpellListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('character_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_class_spell_list_item', to='hyperborea.characterclass')),
                ('spell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell_spell_list_item', to='hyperborea.spell')),
            ],
        ),
    ]
