# Generated by Django 4.2.7 on 2023-12-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperborea', '0011_characterclass_remove_spell_cleric_level_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='spelllistitem',
            constraint=models.UniqueConstraint(fields=('level', 'character_class', 'spell'), name='unique_level_character_class_spell'),
        ),
    ]
